from __future__ import annotations

from pathlib import Path

import pytest
from review_ctx.gitdiff import FileChange
from review_ctx.hygiene import exclusion_reason, filter_changes


@pytest.mark.parametrize(
    ("path", "reason"),
    [
        ("package-lock.json", "lockfile"),
        ("web/yarn.lock", "lockfile"),
        ("pnpm-lock.yaml", "lockfile"),
        ("uv.lock", "lockfile"),
        ("go.sum", "lockfile"),
        ("deps/custom.lock", "lockfile"),
        ("node_modules/left-pad/index.js", "vendored"),
        ("app/vendor/lib/util.php", "vendored"),
        ("third_party/zlib/zlib.c", "vendored"),
        ("web/src/__snapshots__/App.test.tsx.snap", "snapshot"),
        ("web/src/App.snap", "snapshot"),
        ("dist/bundle.js", "generated"),
        ("service/target/classes/App.class", "generated"),
        ("web/build/main.js", "generated"),
        ("static/app.min.js", "generated"),
        ("static/app.js.map", "generated"),
        ("proto/api.pb.go", "generated"),
        ("proto/api_pb2.py", "generated"),
        ("src/Client.generated.ts", "generated"),
        ("Models/Order.designer.cs", "generated"),
        ("src/main/java/shop/OrderController.java", None),
        ("src/build.gradle", None),
        ("src/builder/Builder.java", None),
        ("web/src/vendors.ts", None),
        ("docs/lockfile-policy.md", None),
        ("src/components/Snapshot.tsx", None),
    ],
)
def test_path_rules(path: str, reason: str | None) -> None:
    assert exclusion_reason(path) == reason


def test_directory_rules_match_whole_segments_only() -> None:
    assert exclusion_reason("src/outbound/Sender.java") is None
    assert exclusion_reason("src/out/Sender.java") == "generated"
    assert exclusion_reason("src/distribution/Plan.java") is None


def test_binary_files_are_excluded() -> None:
    assert exclusion_reason("assets/logo.png", binary=True) == "binary"


@pytest.mark.parametrize(
    "header",
    [
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n",
        "/* @generated */\nexport const x = 1\n",
        "# This file was generated by a tool\nA = 1\n",
        "// AUTO-GENERATED, do not modify\nclass A {}\n",
    ],
)
def test_generated_code_markers_in_the_first_lines(header: str) -> None:
    assert exclusion_reason("src/Api.java", header) == "generated"


def test_marker_beyond_the_first_lines_is_ignored() -> None:
    body = "\n".join(["// filler"] * 12 + ["// generated code below"])
    assert exclusion_reason("src/Api.java", body) is None


def test_filter_splits_changes_and_reports_reasons(tmp_path: Path) -> None:
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "A.java").write_text("class A {}\n", encoding="utf-8")
    (tmp_path / "src" / "B.java").write_text("// @generated\nclass B {}\n", encoding="utf-8")
    files = [
        FileChange("src/A.java", "M", additions=1),
        FileChange("src/B.java", "M", additions=2),
        FileChange("yarn.lock", "M", additions=40),
        FileChange("logo.png", "A", binary=True),
        FileChange("src/New.java", "R", old_path="src/Old.java"),
        FileChange("src/Removed.java", "D", deletions=5),
    ]
    kept, excluded = filter_changes(tmp_path, files)
    assert [c.path for c in kept] == ["src/A.java", "src/Removed.java"]
    assert excluded == [
        ("src/B.java", "generated"),
        ("yarn.lock", "lockfile"),
        ("logo.png", "binary"),
        ("src/New.java", "rename_only"),
    ]


def test_renamed_file_with_edits_is_kept(tmp_path: Path) -> None:
    (tmp_path / "New.java").write_text("class New {}\n", encoding="utf-8")
    change = FileChange("New.java", "R", old_path="Old.java", additions=1, deletions=1)
    kept, excluded = filter_changes(tmp_path, [change])
    assert kept == [change] and excluded == []


def test_missing_file_on_disk_is_kept_without_markers(tmp_path: Path) -> None:
    change = FileChange("src/Ghost.java", "M", additions=1)
    assert filter_changes(tmp_path, [change])[0] == [change]
