"""Exclusion of files that carry no reviewable authored code from the diff."""

from __future__ import annotations

import fnmatch
from pathlib import Path, PurePosixPath

from review_ctx.gitdiff import FileChange

LOCKFILES = frozenset(
    {
        "package-lock.json",
        "npm-shrinkwrap.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "Pipfile.lock",
        "uv.lock",
        "Cargo.lock",
        "go.sum",
        "Gemfile.lock",
        "composer.lock",
        "gradle.lockfile",
        "mix.lock",
        "pubspec.lock",
        "packages.lock.json",
        "flake.lock",
    }
)
VENDORED_DIRS = frozenset(
    {"node_modules", "vendor", "third_party", "bower_components", "Pods", ".yarn"}
)
GENERATED_DIRS = frozenset(
    {"dist", "build", "out", "target", ".next", "coverage", "__pycache__", ".gradle", "generated"}
)
SNAPSHOT_DIRS = frozenset({"__snapshots__"})
GENERATED_PATTERNS = (
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.pb.go",
    "*_pb2.py",
    "*_pb2_grpc.py",
    "*.generated.*",
    "*.g.dart",
    "*.g.cs",
    "*.designer.cs",
)
SNAPSHOT_PATTERNS = ("*.snap",)
GENERATED_MARKERS = (
    "@generated",
    "do not edit",
    "code generated",
    "auto-generated",
    "autogenerated",
    "this file was generated",
)
MARKER_LINES = 10


def exclusion_reason(path: str, head: str = "", binary: bool = False) -> str | None:
    """Why ``path`` should not be reviewed, or ``None`` when it should.

    ``head`` is the beginning of the file, searched for generated-code markers.
    """
    parts = PurePosixPath(path).parts
    name = parts[-1]
    directories = set(parts[:-1])
    if binary:
        return "binary"
    if name in LOCKFILES or name.endswith(".lock"):
        return "lockfile"
    if directories & VENDORED_DIRS:
        return "vendored"
    if directories & SNAPSHOT_DIRS or any(fnmatch.fnmatch(name, p) for p in SNAPSHOT_PATTERNS):
        return "snapshot"
    if directories & GENERATED_DIRS or any(fnmatch.fnmatch(name, p) for p in GENERATED_PATTERNS):
        return "generated"
    lowered = "\n".join(head.splitlines()[:MARKER_LINES]).lower()
    if any(marker in lowered for marker in GENERATED_MARKERS):
        return "generated"
    return None


def filter_changes(
    root: Path, files: list[FileChange]
) -> tuple[list[FileChange], list[tuple[str, str]]]:
    """Split ``files`` into those to review and ``(path, reason)`` pairs for those excluded."""
    kept: list[FileChange] = []
    excluded: list[tuple[str, str]] = []
    for change in files:
        if change.status == "R" and not (change.additions or change.deletions):
            excluded.append((change.path, "rename_only"))
            continue
        head = "" if change.status == "D" else _head(root / change.path)
        reason = exclusion_reason(change.path, head, change.binary)
        if reason is None:
            kept.append(change)
        else:
            excluded.append((change.path, reason))
    return kept, excluded


def _head(path: Path) -> str:
    try:
        with path.open(encoding="utf-8", errors="replace") as handle:
            return "".join(handle.readline() for _ in range(MARKER_LINES))
    except OSError:
        return ""
